/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export type Gender = { 'other' : null } |
  { 'female' : null } |
  { 'male' : null };
export type MembershipTier = { 'premium' : null } |
  { 'gold' : null } |
  { 'basic' : null };
export interface Profile {
  'age' : bigint,
  'bio' : string,
  'displayName' : string,
  'membershipExpiry' : Time,
  'interests' : Array<string>,
  'city' : string,
  'gender' : Gender,
  'photo' : [] | [ExternalBlob],
  'membershipTier' : MembershipTier,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'activateMembership' : ActorMethod<[Principal, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createMembershipCheckoutSession' : ActorMethod<
    [string, string, string],
    string
  >,
  'getCallerProfile' : ActorMethod<[], [] | [Profile]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [Profile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMatches' : ActorMethod<[], Array<Profile>>,
  'getMembershipPlans' : ActorMethod<[], Array<[string, bigint]>>,
  'getMembershipStatus' : ActorMethod<
    [Principal],
    [MembershipTier, Time, boolean]
  >,
  'getOppositeGenderProfiles' : ActorMethod<[], Array<Profile>>,
  'getProfile' : ActorMethod<[Principal], Profile>,
  'getProfilesByGender' : ActorMethod<[Gender], Array<Profile>>,
  'getProfilesWithoutPhotos' : ActorMethod<[], Array<Profile>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [Profile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'likeProfile' : ActorMethod<[Principal], undefined>,
  'passProfile' : ActorMethod<[Principal], undefined>,
  'saveCallerProfile' : ActorMethod<[Profile], undefined>,
  'saveCallerProfilePhoto' : ActorMethod<[ExternalBlob], undefined>,
  'saveCallerUserProfile' : ActorMethod<[Profile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];